{% set name = "silicon" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Aloxaf/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 815d41775dd9cd399650addf8056f803f3f57e68438e8b38445ee727a56b4b2d

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - harfbuzz
    - fontconfig
    - freetype
    - libxcb

test:
  commands:
    - silicon --help

about:
  home: https://github.com/Aloxaf/silicon
  summary: Create beautiful image of your source code.
  dev_url: https://github.com/Aloxaf/silicon
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
